name: 'JSON Checker'
description: 'Tools for open source maintainers to auto-triage JSON submissions in a friendly way to contributors'
author: 'Loren Norman'

inputs:
  schema:
    description: 'The JSON Schema file to validate against'
    required: true
  json-files:
    description: 'A globbed list of JSON files to validate'
    required: true

outputs:
  success:
    description: 'Whether validation succeeded or not'
  errors:
    description: 'List of validation errors including line, position, and reason for failure'

runs:
  using: node20
  main: dist/index.js
